---
title: "20161216 meeting"
author: "Yosuke Fujii"
date: "20161216"
output:
  html_document:
    toc: true
    toc_depth: 4 #デフォルト値は2
    number_section: true #trueでナンバリング
---
Created at `r Sys.time()`.

```{r eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, comment=""}
knitr::opts_chunk$set(echo=FALSE, eval=FALSE, warning=FALSE, message=FALSE, comment="",
out.height=480, out.width=480, fig.height=7, fig.width=7)
#knitr::knit_hooks$set(rgl = hook_webgl)
# render("20161216.Rmd"); browseURL("20161216.html")
```

# Rotation of spherical harminics

Parametarization rotation is much faster ($O(b^4)$) than brute force method ($O(b^6)$) for surface alignment ($b$ is the bandwidth).




$v(\theta, \phi)=\displaystyle\sum_{l=0}^\infty\displaystyle\sum_{m=-l}^lc_l^m Y_l^m(\theta, \phi)$ is spherical harmonics parametric surface. After rotating the surface in Euler angle $(\alpha, \beta, \gamma)$, the new coefficients $c_l^m(\alpha\beta\gamma)$ is

$c_l^m (\alpha\beta\gamma)=\displaystyle\sum_{m^{'}=-l}^l c_l^{m^{'}} D_{mm^{'}}^l (\alpha\beta\gamma)$,

where

$D_{mm^{'}}^l(\alpha\beta\gamma)=e^{-im^{'}\alpha}d_{m^{'}m}^l(\beta)e^{-im\gamma}$

and

$d_{m^{'}m}^l (\beta)=\displaystyle\sum_{i=max(0, m-m^{'})}^{min(l+m,l-m^{'})} (-1)^i \frac{\sqrt{(l+m)!(l-m)!(l+m^{'})!(l-m^{'})!}}{(l+m-i)!(l-m^{'}-i)!(i+m^{'}-m)!i!}\left(\cos\frac{\beta}{2}\right)^{2l+m-m^{'}-2i}\left(\sin\frac{\beta}{2}\right)^{2i+m^{'}-m}$.

Disttance between two surface $D(v_1, v_2)$ is defined as

$D(v_1, v_2)=\left(\int ||v_1(s)-v_2(s)||^2ds\right)^\frac{1}{2}=\left(\displaystyle\sum_{l=0}^L \displaystyle\sum_{m=-l}^l ({c_l^m}_1-{c_l^m}_2)^2\right)^\frac{1}{2}$.

Simply, minimizing $D$ as ordinal $L_2$ norm is the best alignment of two surface.

