---
title: "３次元座標を表す球面調和関数係数行列"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## スピン・トランスフォーメーション

閉曲面がスピン・トランスフォーメーションにより単位球面にマップされる。

## 単位球面上の情報

単位球面には、オリジナルの形の対応点の情報が張り付く。

その情報のひとつは、オリジナルの形の３次元座標(x,y,z)である。

## Althloothi et al.の方法

https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6471227 
以下に、Althloothiの方法を概説する。

今、単位球面上の点vを極座標によって$(\phi,\psi)$で表したとする。

今、単位球にはりついた(x,y,z)座標の情報が、それぞれ
$$
f_w(\phi,\psi) = \sum_{l} \sum_{m=-l}^{l} c(w)_m^l  Y_m^l (\phi,\psi);\\
w = x,y,z
$$

と表せているとする。

ここで、オリジナルの物体を、３次元空間で回転することを考える。
その回転をRとすれば、オリジナルの物体表面の点座標 (x,y,z)は
$$
R (x,y,z)^T
$$
に移される。

今、単位球面上の点$v(\phi,\psi)$に張り付いている３次元座標(x,y,z)は、この回転Rにより
$$
R (x,y,z)^T = R \begin{pmatrix} \sum_{l} \sum_{m=-l}^{l} c_m^l(x) Y_m^l (\phi,\psi) \\ \sum_{l} \sum_{m=-l}^{l} c_m^l(y) Y_m^l (\phi,\psi) \\ \sum_{l} \sum_{m=-l}^{l} c_m^l(z) Y_m^l (\phi,\psi) \end{pmatrix}
$$

に移る。

二重の$\sum$があるが、これを$(l+1)^2$の長さのベクトルの計算とすると

$$
R (x,y,z)^T = R W Y
$$
ただし、$R$は$3\times 3$ 回転行列、
$W$ は、$3 \times (l+1)^2$ 行列、
$Y$ は$ (l+1)^2 \times 1$ 行列である。

特定の点$v(\phi,\psi)$にとって、$Y$は球面調和関数が与える特定の値を持つベクトルであるから、

$$
R (x,y,z)^T = (R W) Y
$$

のようにして、３つの球面調和関数分解係数ベクトルを束ねた行列$W$の、各$l,m$での３つ組$(c_m^l(x),c_m^l(y),c_m^l(z))$を、３次元空間の点とみなして、それを回転Rで変換して、新たな係数ベクトルの束を作り、新たにできたx,y,z座標の球面調和関数分解係数ベクトルに対して、球面調和関数をあててやることで、$v(\phi,\psi)$に対応づく３次元座標は、オリジナルの形を３次元空間で回転Rした座標となることがわかる。

Althloothi et al.は、このような回転によって、球面調和関数分解係数列の束を変化させ、別の形のそれとのエレメント・ワイズな差の２乗ノルムが最小になるような回転Rが線形代数的にも止まることを示した。

## 球面調和関数係数ベクトルの空間と２種類の回転

上記では、オリジナルな３Ｄ物体がその三次元空間で回転した。

そのとき、オリジナルな３Ｄ物体は、「置かれ方」は変わるが、形(も大きさも)は変わらない。

それとは別に、球面調和関数たちが張り付いた単位球も三次元空間の物体なので、回転することができる。
そのようにしてできる単位球面上の場(模様)は変わらない。

この２種類の回転はどういうことなのか、を考えたい。

### ウサギ1

ウサギをスピン・トランスフォーメーションして球化する。
３次元空間のこのウサギをU1、球化されたそれを、Us1($3\times (l+1)^2$ 行列)とする。

### ウサギ2

別のウサギ U2を考える。
このU2は、U1を三次元空間でR回転したものとする。
U2をスピン・トランスフォーメーションし、その結果をUs2とする。

Us2(x,y,z座標に関する球面調和関数分解係数行列)をUs1にあわせるために、最適回転$\hat{R}$をAlthloothi法で得ると、$\hat{R} \sim R$である。

このとき、Us2は$\hat{Us2}$に変化するが、$\hat{Us2} \sim Us1$である。


$$
R Us2 =  Us1\\
\hat{R} Us2 = \hat{Us2} \sim Us1
$$

## 気になること

ここで、$\hat{Us2}$の係数は、(x,y,z)に対する係数$(c_m^l(x),c_m^l(y),c_m^l(z))$を回転Rしたものであって、必ずしも、球面調和関数係数をWignerD等で回転(単位球面上での回転変換)して得られたものではない。

WignerDでの変換の場合、球面調和関数係数は各レイヤーごとに

$$
\sum_{m=-l}^l (c_m^l)^2
$$
が保たれる性質があるが、

このAlthloothi変換はこれを保つものではない。

しかしながら、$c_m^l(x,y,z)$が得られているので、$\hat{Us2}$は各レイヤーでの２乗ノルム条件を満足していると思われる。

本当かどうか確かめたい。

* もし満足しているのなら：$Us2$を$\hat{R}$に限らず、任意のRで回転してやったときにできる新たな係数行列では、各lレイヤーごとの二乗ノルムは保たれているんだろうか？保たれていないのに、相変わらずウサギを表しているとはどういうことだろうか？
* もし満足しているとしたら、$Us2$をWignerD回転して$Us1$にするような回転はないのだろうか、あるのだろうか。

* もし満足しているとしたら、そもそも、$c^l_m(x),c^l_m(y),c^l_m(z)$って言うのは、てんでんばらばらな値ではなくて、相互に制約のある値になっていたりするのではないか。制約があるとするとどんな制約なのか。

* もし満足していないのなら：$\hat{Us2}$が球面に作る模様と$Us1$が球面に作る模様は違うはずなので、それを絵にしてみてみたい。

## 気になること２

Us1を単位球面でWignerD回転すると、球面上の模様は「ずれる」けれどパターンは変わらない。
これをUsW1とします。
Usw1には各所に(x,y,z)座標が張り付いているけれど、その座標自体はUs1のそれと変わっていないです。

これがどういうことか、というと、U1というウサギ(置かれ方も決まっているウサギ)の表面の座標を表す球面調和関数分解係数行列は、いくつもある(Us1をWignerD回転したすべてがそう)のだが、U1をスピン・トランスフォーメーションして得られるのは、Us1だけ、ということになる。

これは、
三次元空間の実在が『スピン・トランスフォーメーション』で単位球にマップされたときの球面調和関数分解係数ベクトルは、ベクトルの空間の全体ではなくて部分空間になっているのではないか、ということ。

これが、気になること１とも関係しているような気がします。

そうすると、

