---
title: "数学の問題"
output: html_document
---

# こんな問題はどう考える？

n個の点が、m次元空間の点として与えられている。

その座標を$x_i^T = (x_{i1},x_{i2},...,x_{im}); i = 1,2,...,n$ とする。

今、ある対角行列 $M$があり、その$M$の対角成分は、$\pm 1$のいずれかであると言い、この$M$を使うと、すべての点で

$$
x_i^T M x_i = 1
$$
であると言う。

今、$M$を用いて$d_{ij}$を次のように定める。

$$
d_{ij}^2=d_{ji}^2 = 2 - 2x_i^T M x_j
$$

この$d_{ij}$には次のような関係が調べたくなると言う。

ある、トリオ$(i,j,k),i\ne j, j \ne k,k \ne i$があったとき、

$$
d_{ij} + d_{jk} = d_{ki} \\
d_{jk} + d_{ki} = d_{ij} \\
d_{ij} + d_{ki} = d_{jk}
$$

の３等式のいずれかを満足するとき、$(i,j,k)$を「よいトリオ」と呼び、
３等式のいずれもが満足されないとき、$(i,j,k)$を「悪いトリオ」と呼ぶことにする。

ここで、知りたいのは、$(i,j,k)$たちの「よい/悪い」のラベル付けの「パターン」と、$X=\begin{pmatrix}x_1,x_2,...,x_n \end{pmatrix}$と$M$とがもつ特性との関係である。

# グラフ距離としての意味をつけて意訳する

上記の問題を意訳すると以下のようになる

* n個の点は、グラフの頂点
* m次元空間は、(非正定置)内積行列を用いた座標系で張られている
* トリオ$i,j,k$は３頂点のトリオであって、今、iからkへの最短経路上にjがあるとき $d_{ij} + d_{jk} = d_{ki}$ が成り立つ
* 頂点数 x 頂点数 x 頂点数 の3次元アレイ$A$を考えるとき、良いトリオ$(i,j,k)$に対して、$A[i,j,k]=1$とすることで、グラフ上の最短経路全体の情報に対応付けることができる


なお、予想されることとしては、次のことがある。

* $M$の性質には、グラフが閉曲面を表しているとき(平面グラフであるとき)に満足する性質と、それに付加的に満足するべき性質とがあり、後者が、「形」の特徴を表している

# 半順序集合　ポセット

さて。

$(i,j,k)$たちの「よい/悪い」のラベル付けを考えるために、こんな風に考えることができるのではなかろうか。


集合$N = \{1,2,...,n\}$の部分集合$\sigma$があったとき、$\sigma$の要素が作るすべてのトリオが「よい」場合と、逆にすべてのトリオが「悪い」場合とがあれば、この部分集合$\sigma$は「よい部分集合/悪い部分集合」とラベル付けしてくくってしまうことができる。


のうち、要素数がt個のものを集めた部分集合を
$S_t$と表すことにする。

今、$S_0,S_1,S_2,S_3$を併せた部分集合を$S_{\le 3}$とする。

この$S_{\le 3}$には、包含関係があり、半順序をなしている。

この半順序集合の一番の底は$\phi$であり、$\phi$は$S_0$の唯一の要素である。

