---
title: "閉曲面の幾何"
author: "ryamada"
date: "2018年10月12日"
output: html_document
---

# 閉曲面上の直線

直線線分を「2点を通る最短距離となる曲線分」と定義する。

このとき、「測地線」が曲線上の直線に相当し、「最短パス」がグラフ上の直線に相当する。

# 閉曲面上の首

閉曲面上に自己交叉の無い閉曲線があり、その閉曲線上の任意の2点間の「直線〜測地線」が、その閉曲線自身であるとき、その閉曲線を「首」と定義する。

## 首の性質

### 2つの首は、相互に交叉しない

今2つの首が交叉しているものとすると、2つの首をベン図と見たときの「交わり」に相当する部分が、やはり首である。したがって、この場合には、3つ首が並び、隣り合う首同士は曲線分を共有しているとみなすことにする。

このように定義すると2つの首は交叉しないことになる。

### 首は閉曲面を2領域に分ける

首に限らず、自己交叉を持たない閉曲線は平曲面を2領域に分ける。

### 首によって分けられた2領域上の片方の領域にある2点の間の測地線は首をよぎらない

もしもその測地線が首をよぎるとすると、その測地線と首との2つの交点の測地線は、よぎっている測地線となるが、それは、首の定義に反するから、そのような測地線はない。

### 首によって分けられた2領域上の2つの領域にそれぞれ属する2点間の測地線は、首をただ1回よぎる

2点は首によって隔てられているから、2点間の測地線は首を1回以上よぎらなくてはならない。しかしながら、同一領域内の2点を結ぶ測地線は首と交叉しないから、交叉回数は1回であって、それより多くはない。

# 首により、閉曲面は木構造として表される

## 首が作る木

首と首が分ける2領域の関係は、首をエッジとして、2領域をエッジの2端点とみなすことができる。

今、閉曲面上に1個以上の首があるとする。その首の配置は、首の内部(首が作る2領域の片方の領域)に首が配置されることで、首の数は増える。
また、首によって区画されたある領域内に、相互に交わらない複数の首が配置されることもある。

いずれにしろ、首をエッジとして、首によって区画される領域をノードとすると、それはグラフとなり、かつ、このグラフは木構造である。

## 首が作る木のノードとエッジは部分グラフ

閉曲面にあって、首は閉曲線であり、首によって区画される領域は、開領域である。

閉曲面全体を平面グラフと見れば、首はサイクルグラフであり、首が区画する部分領域は部分グラフである。

# 首間の測地線の様相

## 首接線と首接点

簡単のために、平面上に２つの円があり、その円は交叉せず、包含・被包含関係にもないものとする。

このとき、片方の円周上の点から、もう片方の円周上の点への直線を引くことを考える。

2つの円周上の2点が作るペアの最短距離のうち、最も短いものは、2つの円の中心を結んだ線分の交点である。

片方の円C1の中心から、もう片方の円周C2に接線2本を引く。この2本の接線のC2上の2つの接点が挟むC2の弧の上の点からC1への最短路はC1の中心への直線がC1をよぎる点である。
C2上の接点が作る弧よりも外側のC2上の点から、C1上への点への最短路であって、C2の内部を通らないものは、C2上の接点まではC2に沿い、C2上の接点からC1の中心へと向かう直線を通るものである。

ここでは、平面・円周で考えたが、これを閉曲面・首に置き換える。

直線は測地線に、測地線が通れない円周内部領域は首の内部領域に相当するので、同様に、首-首間の接線相当測地線分と、接点に相当する首上の点が定義できそうである。

これを、首接線、首接点と呼ぶことにする。

また、首-首間の最短パスを首間最短測地線と呼ぶことにする。

なお、首接線・首接点は、2つの首C1,C2があったときに、(C1,C2)と(C2,C1)についてそれぞれ別々に決まるものである。

### 首接線・首接点の有用性

この首接線・首接点は、首の内部から別の首の内部への測地線を調べるときに有用となる。

首をよぎる測地線は、始点から首上のすべての点までの測地線と、首上のすべての点から終点までの測地線とのペアワイズな組み合わせについて考慮し、長さの和が最小になる組み合わせを見出すことで決定できる。

さらに、始点と終点とが、首によって連結しない、より離れた領域にそれぞれ属する場合には、首木構造に着目し、中間に介在する領域については、首上の点ともう一つの首上の点とを結ぶ測地線について考えるだけでよい。

このように、考慮するべき要素を減じることができる点は有用であると考えられる。


## 首橋と首橋袂点

平面にある２つの円周をふただび考える。

この２つの円周の周囲に紐をかけることを考える。

自転車のチェーンを二つの歯車にかけるような要領である。

このとき、チェーンが巻きついているところと巻きついていないところがある。また、二つの歯車を橋渡しする直線状のチェーンがある。

この２つの歯車を首に置き換えたときの直線状のチェーンを、首橋、その首に着地する点を、首橋袂点と呼ぶことにする。

この首橋とその袂点は、２つの首の(順序無視)ペアに対して決まる。

### 首橋・首橋袂点の有用性

この首橋は、橋を構成する複数の首の両方に接する領域内の点間の測地線を調べる際に有用である。

ある領域中に二つの首があるとする。この領域に含まれる2点間の測地線を考えるとき、2点が、2つの首橋にはさまれた領域の外にあるときには、その領域を測地線が通るか否かについて、場合わけをすることができるのではないかと予想される。そのような発想により、同一領域内の2点間測地線について、何かしらの有用な活用法がある可能性がある。


# 首関連幾何対象による閉曲面の分解

閉曲面$\Omega$に、首の集合$\mathbf{C}=\{C_1,...,\}$があったとする。

ここには$|\mathbf{C}|$個の首があり、首によって分けられる領域が$|\mathbf{C}|+1$領域ある。
この領域を$\mathbf{A} = \{A_1,...\}$とすると、$G=(\mathbf{A},\mathbf{C})$というグラフがあり、これは木グラフである。

今、ある領域$A_i$に接続するエッジが首$\mathbf{C}_{A_i} = \{そC_{A_i, 1},...\}$であるとすると、

$|\mathbf{C}_{A_i}| \times |\mathbf{C}_{A_i}|$ 通りの首の順序つきペアがある。

それぞれのペアについて第一の首上の点から、もう片方の首への測地線を引くことを考えると、そのペアについて、首接線と首接点と首間最短測地線とが定まる。

首ペアが自身と自身のペアの場合は特別で、その場合は首間最短測地線が無数に引けて、首接線と首接点とは定義されないものとする。

首橋と首橋袂点とは
$\frac{|\mathbf{C}_{A_i}| \times (|\mathbf{C}_{A_i}|-1)}{2}$のペアに定まる。


# 首関連幾何対象による閉曲面上の測地線集合の分解

上記の幾何対象を考慮すると、閉曲面上の任意の2点間の測地線は、2点と幾何対象との関連を考慮することによって、部分的な情報を用いるだけで定められよう。

さて、その限局情報とはどのように記載すればよいか。
それに何かしらのメリットはあるか。

そもそも、幾何対象を(定性的に)扱うことで、「おおまかな形」についての情報は得られるだろうか？

# 首と「くびれ」

閉曲面上のサイクルであって、任意の2点間の測地線が常にそのサイクル上にあるものを「首」と定義した。

この「首」は３Ｄオブジェクトとして見たときに、「くびれている〜紐でぎゅっと縛れる」かどうかというと、そうではない。

「首」と「くびれ」とは別物である(『首』という呼称が誤解を招くものだ、ということになる)。

では、「首」はどういうものか、というと。

* 球の上に、球が乗っていて、その乗っている球が、下の球と接する交差曲線が、赤道よりも南極寄りの場合に、「くびれ」ている。

* また、上に乗っている球が、ちょうど赤道で接していたのだが、乗っている球が、上方に延びる(結果として楕球が乗っているような状況)と、やはり、それは「首」である。しかしながら、この首を紐で縛れろうとしても、紐は上に抜けていってしまう。したがって、これは「くびれ」ではない。ちなみに、この楕球が乗っているタイプの「首」の場合、「首」のすぐ上に「首」があり、「延々と首が並ぶ」




