---
title: "行列はありがたい"
author: "ryamada"
date: "2017年6月12日"
output: 
  html_document:
    toc: true
    toc_depth: 6
    number_section: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 行列はありがたい

##	行列の演算，単位行列，逆行列

### 行列の演算
$$
\frac{\Delta x}{\Delta t} = p x + q y\\
\frac{\Delta y}{\Delta t} = r x + s y
$$

```{r}
delta.t <- 10^-3
n.step <- 10^4
p <- 1
q <- -2
r <- 3
s <- -2
M <- matrix(c(p,q,r,s),byrow=TRUE,ncol=2,nrow=2)
M
xy <- matrix(0,2,n.step)
xy[,1] <- c(3,5)

delta.xy <- M %*% xy[,1]

delta.xy
p * xy[1,1] + q * xy[2,1]
r * xy[1,1] + s * xy[2,1]
delta.xy * delta.t
```
```{r}
for(i in 2:n.step){
  dxdy <- M %*% xy[,i-1] * delta.t
  xy[,i] <- xy[,i-1] + dxdy
}
plot(xy[1,],xy[2,],type="l")
```
### 簡単に書ける、一般化できる

$$
\frac{\Delta x}{\Delta t} = p x + q y\\
\frac{\Delta y}{\Delta t} = r x + s y
$$
$$
\frac{\Delta x_1}{\Delta t} = m_{1,1} x_1 + m_{1,2} x_2 + m_{1,3} x_3\\
\frac{\Delta x_2}{\Delta t} = m_{2,1} x_1 + m_{2,2} x_2 + m_{2,3} x_3\\
\frac{\Delta x_3}{\Delta t} = m_{3,1} x_1 + m_{3,2} x_2 + m_{3,3} x_3
$$
$$
\frac{\Delta x_i}{\Delta t} &= m_{i,1} x_1 + m_{i,2} x_2 + m_{i,3} x_3
$$
$$
\frac{\Delta x_i}{\Delta t} = \sum_{j=1}^3 m_{i,j} x_j
$$

$$
\begin{pmatrix}
\frac{\Delta x_1}{\Delta t}\\
...\\
\frac{\Delta x_n}{\Delta t}
\end{pmatrix} = \begin{pmatrix}
m_{1,1},m_{1,2},...,m_{i,n}\\
...\\
m_{n,1},m_{n,2},...,m_{n,n}
\end{pmatrix} \begin{pmatrix}
x_1\\
...\\
x_n
\end{pmatrix}
$$

$$
\frac{\Delta \mathbf{x}}{\Delta t} = M \mathbf{x}
$$

### 4要素でシミュレーション

$x_1$と$x_2$の関係は2要素シミュレーションで用いた関係であり、
$x_3$と$x_4$の関係も同じだとする。

$x_2$と$x_3$とに「$x_2$は$x_3$の量に応じて増え」「$x_3$は$x_2$の量に応じて減る」という関係を入れてみよう。

2要素の行列
```{r}
delta.t <- 10^-3
n.step <- 10^4
p <- 1
q <- -2
r <- 3
s <- -2
M <- matrix(c(p,q,r,s),byrow=TRUE,ncol=2,nrow=2)
M
```

4要素に拡張
```{r}
M4 <- matrix(0,4,4)
M4[c(1,2),c(1,2)] <- M
M4
M4[c(3,4),c(3,4)] <- M
M4
# x2,x3の関係
a <- 3
b <- -2
M4[2,3] <- a
M4[3,2] <- b
M4
```
```{r}
x4 <- matrix(0,4,n.step)
x4[,1] <- c(3,5,3,5)

delta.x4 <- M4 %*% x4[,1]

delta.x4 * delta.t
```


```{r}
for(i in 2:n.step){
  dx <- M4 %*% x4[,i-1] * delta.t
  x4[,i] <- x4[,i-1] + dx
}
plot(x4[1,],x4[2,],type="l")
plot(x4[3,],x4[4,],type="l")
plot(x4[2,],x4[3,],type="l")

matplot(t(x4),type="l")
```

#	線型差分方程式・線型微分方程式の行列を用いた表記
#	行列の対角化（実固有値の場合）
#	対角化による線型微分方程式の解法
#	平衡点のおける線型化微分方程式