---
title: "Research idea"
author: "Daigo Okada"
date: "2017年12月15日"
output: 
  html_document:
    toc: true
    toc_depth: 6
    number_section: true
---

# 現在のデータ
・各サンプルのMDS座標

・免疫表現型の個人差に関与していそうなパスウェイのリスト

・免疫表現型の個人差に関与していそうなSNPのリスト

・各サンプルのリンパ球サブセットの存在割合の行列　（サンプル数　×　64サブセット）

# 背景
・免役の個人差に影響を与えるSNPリストが得られたが、実際にそのSNPがどのような生物学的機構を介して、
リンパ球プロファイルに影響を与えているかは不明である。


# 概要
・SNPジェノタイプは遺伝子発現値に影響を与えるが、その与え方は細胞の種類ごとに異なる。

・FACSデータは末梢血の細胞の集まりである。

・マイクロアレイデータは末梢血の個々の細胞の遺伝子発現をならして平均化した値が得られている。


以上の3点を階層ベイズモデルで表現し、各候補SNPがどのような細胞種のどのような遺伝子発現を介して、

MDS座標で表現される個人差につながっているのかを調べる。

# モデル1
・候補SNPをGWASで検出されたSNP1, SNP2、それぞれのアレルの数をg1,g2とする.

・注目遺伝子をa,、そのマイクロアレイでの発現値をexp_aとおく。

・注目する免役細胞subsetをsub1, sub2とする。

・各サンプルでのsub1、sub2の細胞数をnum_sub1, num_sub2とする。

・SNP1がリンパ球サブセットsub1で遺伝子aに与える影響をeffecめんめんt_11aとおく。他も同様に命名する。

以上を踏まえて以下のようなモデルを立てる。

$$
total[i] =  numsub1[i] +  numsub2[i]\\
prosub1[1] =  numsub1[i]/total[i]\\
prosub2[i] =  numsub2[i]/total[i]\\
effecttotal[i] =prosub1 *(g1[i] * effect11a + g2[i] * effect21a) + prosub2 *(g1[i] * effect12a + g2[i] * effect22a)\\
expa[i] \sim Normal(effecttotal[i], {\sigma})
$$

候補SNP、候補遺伝子は、比較的ゆるやかな閾値でGWASの結果から選択する。

各サンプルiの numsub1, numsub2, g1, g2はすでに得られている。

effect11a、effect11bなどの事後分布を得ることで、各SNPと免疫細胞サブセットの関係を調べる。

# モデル2 (モデル1に時系列を考慮する)
さらに、リンパ球サブセットの割合は時系列によって変わるので、それを組み入れる。

ワクチン接種によってリンパ球サブセットの割合が変わり、

その結果マイクロアレイの遺伝子発現値が変動するというモデル。


$$
\lambda[person,t-1] = exp(b1[t-1] + b2[t-1] * numsub1[t-1])\\
numsub1[person,t] \sim Poisson(\lambda[person,t-1])
$$
各被験者personごとに、それぞれの時刻のFACSデータ、マイクロアレイデータがあるので、

モデル1にこれを加え、b2の事後分布を確認することで、ワクチン接種することによる、

サブセット1の変化を追跡する。


# モデル3(リンパ球サブセットの割合に仮定を入れる→マーカー発現パターンの分布に混合正規分布を使う)
モデル2では、個々の細胞サブセットについて、仮定を入れなかった。

FACSのj番めのマーカー発現パターンは混合正規分布を当てはめることができる。

モデル3ではこの仮定をモデル化する。２つの正規分布はそれぞれマーカー陽性、マーカー陰性を表すため、

各リンパ球サブセットは、陰性・陽性の存在比(ratio)のべき乗で表せる。

例えば、６マーカー(マーカー1~6)の陰性(0)と陽性(1)のパターンが111000の細胞サブセットの割合$prosub_{111000}$

と表すと、


$prosub_{111000}=ratio_{1,pos}*ratio_{2,pos}*ratio_{3,pos}*ratio_{4,neg}*ratio_{5,neg}*ratio_{6,neg}$

と表せる。

FACSデータから細胞iのマーカーjの発現値が得られているので、モデル2に以下の式を付け加えることで、

混合正規分布のパラメータのベイズ推定をしつつ、免疫細胞サブセットの割合を決める。

すでに修論で混合正規分布のフィティングの結果は得られているので、これを事前分布として用いる。


$$
marker[i,j] \sim mixtureNormal(\mu_{j,pos},\mu_{j,neg},\sigma_{j,pos},\sigma_{j,neg},ratio_{j,pos})
$$

# モデル4(リンパ球サブセットの割合に仮定を入れる→細胞の分化を考慮する)

６マーカーの陰性(0)陽性(1)パターンは、64通りの0か1の６つの並びで表せる。

各マーカーごとに、一定時間の間に、マーカーが陽性から陰性に変わる確率、陰性から陽性に変わる確率を定義できる。

マーカーiが0から1にかわる確率は$p_{i,1}$、１から0にかわる確率は$p_{i,0}$と表す。

そう置くことで、6マーカーならば合計12個のパラメーターでリンパ球の分化が記述できる。

例えば000000が000011に単位時間あたりに変化する確率は、$p_{5,1} \times p_{6,1}$

この$p_{i,0}$や$p_{i,1}$がワクチン接種によって変化すると考える。

各SNPの免疫細胞サブセットごとの効果に加え、ワクチン接種によってどのようにリンパ球プロファイルの変化が起こるかを求める。
