
title: "形プロジェクトの相互干渉"
author: "ryamada"
date: "2018年5月19日"
output: html_document
---

# はじめに

形プロジェクトには複数のメンバーが関わっています。

これまでは、それぞれの仕事が比較的独立していましたが、ここへきて、相互の寄与関係が濃くなってきています。

各メンバーの仕事の間の取り持ちを、原則として山田が担ってきましたが、アイディアのシェア・コードのシェアが重要になりつつあるので、メンバーのペアワイズで濃厚にディスカッションを進め、コードのシェアをしてもらいたいと思います。

この文書は、そのシェアリングにあたって、山田が、今日の時点で重要視している項目を理解するために書いています。

解っても解らなくても通読してください。

自分の仕事に関わる部分は理解できるだろうと思います。
自分に関わる部分と関係する、と記載されている項目について、当該項目の主担当者とディスカッションを進めてください。

主担当者自身も理解が曖昧(山田との完全な擦りあわせに至っていない)点も少なくないかもしれません。

ディスカッションにあたり、説明側・被説明側、どちらかでも疑問が残る場合には、山田の確認を取る等、放置しないようにしてください。

# 形と球面上スカラー分布

## メインの考え方(吉安さん)

形を構成する閉曲面は、無限個の点の集合であって、隣接関係があるものです。

形を決める大きな要素に、「任意２頂点間の最短距離」情報があります。
「最短経路」が定まると、「最短距離」も決まるので、「任意２点間の最短経路」情報が形を決める大きな要素であるとも言えます。

形が単位球面に滑らかに写像されるとき、無限個の点が単位球面を埋め尽くします。
埋め尽くす時に、点は濃淡を作ります。

今、濃淡スカラー場を持つ単位球面の移動を考えます。濃度の逆数に比例した速さで運動するとすると、
最短経路は、この運動体が最短時間で到達する経路が「最短時間経路」となります。

この「最短時間経路」と、オリジナルな形の上の「最短経路」は同じと考えられます。

したがって、形を単位球面上の頂点の濃淡分布として取り出すことにします。

## ガウス曲率の取り出し(藤井さん・高岡さん)

吉安さんは濃淡分布を取り出したいです。それは、オリジナルの形のガウス曲率と関連して定められると
予想しています。
ガウス曲率を取り出して吉安さんが使えるようにする必要があります。

## 濃淡分布の球面調和関数分解(高岡さん)

球面上スカラー場の球面調和関数分解は、平均曲率・ガウス曲率についても行いますが、吉安さんが取り出すだろう、濃淡分布にも行います。

## 球面スカラー場の３次元座標化とその球面調和関数分解(高岡さん)

上記で複数の球面上スカラー場の球面調和関数分解を使うことを述べましたが、複数の球面上スカラー場分解を比較するためには、アラインメントが必要です。

アラインメント問題は、球面に３次元座標が張り付いているときには線形代数的に解けることが知られているので、スカラー場の３次元座標化は、それをさらにアラインメントに用いることができるこを含めて示すことが必要です。

## アラインメント(藤井さん)

アラインメントは何かしらの方法で必ず行う必要があります。

形を比較する、分布を比較する、という比較課題に必要です。

また、変形を伴う形の時間変化を分解するためにも必要です。

Althloothi法で可能であろうという結論にほぼ終息していますが、周辺問題が解決されていません。

周辺問題の解決と、実装にあたってどういう理由で、どれを採用するかの確定が必要です。

## 球面上分布の指数型分布族推定とKLd(岡田さん)

単位球面上の濃淡分布は、総積分＝１で標準化すれば、確率密度分布と同じです。

単位球面を(できるだけ)等面積区画に分けることで、離散化し、指数型分布族推定することもできるでしょう。

したがって、単位球面上の各頂点(各三角形)のガウス曲率の出力を吉安さんが使えるようにツールの説明・入出力の説明をしてください。

異なる濃淡分布からKLdを算出ことも、形・グラフの異同計量との比較(吉安さん)の検討に必要です。

アラインメントした上でのKLd算出が(も)必要です。

## ガウス曲率か、平均曲率＆ガウス曲率か(和田さん)
)

閉曲面の点間最短距離問題はガウス曲率を基準にするように上記では書きました。

それは、曲率のびろびろ具合はガウス曲率が定めるからです。

しかしながら、和田さんは、平均曲率とガウス曲率との組わせで４色グラフ特徴量を検討しています。

(おそらく、ですが)ガウス曲率は確かにびろびろ加減を表すのですが、ガウス曲率だけだと凹と凸との区別ができません。

実際には閉曲面になるためには、同じガウス曲率でも、ここは凹、ここは凸であるべき、という制約が入ると予想されます。

それについて、ボクセルベースでの単純化四角化グラフが構成する、代数的(？)記述・制約を検討しています(吉安さん)。

和田さんの４色グラフと交点が見いだされるはずです。

## 凹凸の広がりと、凹凸要素の積分・平均(和田さん、吉安さん、岡田さん)

形の凹凸は局所的な特徴です。

しかしながら、それを巨視的に眺めると、より大きな凹凸も捉えることができます。

和田さんの三角メッシュ上の４色グラフてき凹凸抽出も、粗視化が必要です。
観察量の平滑化として捉えることができるかもしれません。

一方、ボクセルベースで単純化した凹凸局所情報があります(吉安さん)。

こちらも、微視・巨視の両方の視点が導入されるべきです。

この巨視化はスムージングでも行けそうですが、グラフ化されている場合には、KNN的アプローチが有効な可能性も高いです。

ノンパラで行く、と言うことです。ノンパラは、指数型分布族表現という点で、やはり岡田さんにつながります。

## 形をおさめた空間(形空間)と、その帰無分布(吉安さん　三村先生　岡田さん　山田)

形を何かしらでとらえたとすると、どんな形がどれくらいの割合で存在しているのか、を問題にすることができます。

完全にランダムな形としてブラウニアンマップという概念が知られています。

ブラウニアンマップのランダム発生には２つの方法があります。

１つは、ランダムに木を作成し、そのエッジにランダムに-1,0,+1をラベル付するという方法です。

ブラウニアンマップと木については、山田もコードを提供しています。


圧縮の分野との関係がありそうと考えています(三村先生)。

もう一つは、球面上のランダムな粗密分布を発生させる方法です。

球面上のランダムな粗密分布は、ガウシアンプロセスと言ったノンパラベイズが有効であると予想されます。

単位球面上のノンパラ分布発生について、一番近いのは岡田さんです。

## 細胞の形集計(高岡さん)

細胞の特徴量抽出(球面調和関数係数列、４色グラフ、球面上濃淡分布、ラベル付き木、球面分布からの指数型分布族表現)を行い、その分布を取ります。

その分布は、帰無分布と比較することで、「細胞らしい形」というものが決まり得ます。
検定をするなら、帰無分布は必要です。

帰無分布は理論的に示せるかもしれませんが、示せないかもしれません。

示せないなら、ブラウニアンマップのランダム生成２方法から作る必要が出る可能性があります。

## 双曲幾何の離散化と鉤針編み(吉安さん　山田)

のたくる形を離散表現しようとしています。
双曲鉤針編みという手法(数学分野)があります。
これと、ボクセルの四角化グラフの頂点次数の広がりには、関係があるように思います。

特に、「閉じる」条件などについて、示唆が大きいと思います。

"http://d.hatena.ne.jp/ryamada/searchdiary?word=%2A%5B%C1%D0%B6%CA%B4%F6%B2%BF%B3%D8%5D"

